/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inicio;

import alumno.Login_alumno;
import coordinador.Login_coordinador;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import maestro.Login_maestro;

/**
 *
 * @author ar275
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        configuracion_ventana();
        cargar_img();
        
        
        //Añadir el listener para detectar cuando la ventana es redimensionada
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                int panelWidth = panel_contenido.getWidth();
                int panel_heigth = panel_contenido.getHeight();
                int newX = (fondo.getWidth() - panelWidth) / 2; // Calcular la nueva posición en 
                int newY = (fondo.getHeight() - panel_heigth) / 2;
                panel_logo.setSize(fondo.getWidth(), panel_logo.getHeight());
                panel_contenido.setLocation(newX, newY);
                logo_ita.setLocation(newX, logo_ita.getY());
            }
        });
    }

    //Funcion para toda la configuracion de la ventana 
    private void configuracion_ventana(){
        //Cargar texto en descripcion
        lb_info_alumno.setText("<html><center>Apartado para estudiantes y candiadatos a ingresara a la institucción.</center> </html>");
        lb_info_maestro.setText("<html><center>Apartado de docentes de la institución.</center> </html>");
        lb_info_coordinador.setText("<html><center>Apartado de coordinadores de la institución.</center> </html>");
        
        //Centrar ventana
        this.setLocationRelativeTo(null);//La ventana aparece en el centro
    }
    
    //Funcion para cargar imagenes
    private void cargar_img(){
        //CARGAR EL LOGO PRINCIPAL DEL TEC
        Image logo_ita_img= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo_ITA.png"));
        logo_ita.setIcon(new ImageIcon(logo_ita_img.getScaledInstance(logo_ita.getWidth(), logo_ita.getHeight(), Image.SCALE_SMOOTH)));
        
        //CARGAR ICONOS PARA LOS BOTONES DE ALUMNO, MEAESTRO Y COORDINADOR
        //Alumno
        Image icon_alumno= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icon_alumno_inicio.png"));
        btn_alumno.setIcon(new ImageIcon(icon_alumno.getScaledInstance(btn_alumno.getWidth(), btn_alumno.getHeight(), Image.SCALE_SMOOTH)));
        //Maestro
        Image icon_maestro= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icon_maestro_inicio.png"));
        btn_maestro.setIcon(new ImageIcon(icon_maestro.getScaledInstance(btn_maestro.getWidth(), btn_maestro.getHeight(), Image.SCALE_SMOOTH)));
        //Coordinador
        Image icon_coordinador = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icon_coordinador.png"));
        btn_coordinador.setIcon(new ImageIcon(icon_coordinador.getScaledInstance(btn_coordinador.getWidth(), btn_coordinador.getHeight(), Image.SCALE_SMOOTH)));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        panel_contenido = new javax.swing.JPanel();
        btn_maestro = new javax.swing.JLabel();
        btn_alumno = new javax.swing.JLabel();
        btn_coordinador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_info_coordinador = new javax.swing.JLabel();
        lb_info_alumno = new javax.swing.JLabel();
        lb_info_maestro = new javax.swing.JLabel();
        panel_logo = new javax.swing.JPanel();
        logo_ita = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        fondo.setBackground(new java.awt.Color(51, 51, 255));
        fondo.setPreferredSize(new java.awt.Dimension(800, 600));
        fondo.setLayout(null);

        panel_contenido.setBackground(new java.awt.Color(51, 51, 255));
        panel_contenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_maestro.setText("jLabel1");
        btn_maestro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_maestro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_maestroMousePressed(evt);
            }
        });
        panel_contenido.add(btn_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 160, 160));

        btn_alumno.setText("jLabel1");
        btn_alumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_alumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_alumnoMousePressed(evt);
            }
        });
        panel_contenido.add(btn_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 160, 160));

        btn_coordinador.setText("jLabel1");
        btn_coordinador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_coordinador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_coordinadorMousePressed(evt);
            }
        });
        panel_contenido.add(btn_coordinador, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 160, 160));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COORDINADOR");
        panel_contenido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 160, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ALUMNO");
        panel_contenido.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 160, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MAESTRO");
        panel_contenido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 160, 40));

        lb_info_coordinador.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lb_info_coordinador.setForeground(new java.awt.Color(255, 255, 255));
        lb_info_coordinador.setText("Descrip coordinador");
        lb_info_coordinador.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panel_contenido.add(lb_info_coordinador, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 160, 130));

        lb_info_alumno.setBackground(new java.awt.Color(0, 242, 242));
        lb_info_alumno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lb_info_alumno.setForeground(new java.awt.Color(255, 255, 255));
        lb_info_alumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_info_alumno.setText("Descrip alumnos");
        lb_info_alumno.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panel_contenido.add(lb_info_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 160, 130));

        lb_info_maestro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lb_info_maestro.setForeground(new java.awt.Color(255, 255, 255));
        lb_info_maestro.setText("Descrip maestro");
        lb_info_maestro.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panel_contenido.add(lb_info_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 160, 130));

        fondo.add(panel_contenido);
        panel_contenido.setBounds(0, 90, 800, 390);

        panel_logo.setBackground(new java.awt.Color(255, 255, 255));
        panel_logo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_ita.setText("LOGO ITA");
        panel_logo.add(logo_ita, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 80));

        fondo.add(panel_logo);
        panel_logo.setBounds(0, 0, 800, 90);

        getContentPane().add(fondo, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_alumnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_alumnoMousePressed
        if(SwingUtilities.isLeftMouseButton(evt)){//Verifica que se de click izquierdo
            Login_alumno ventana = new Login_alumno();
            ventana.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_alumnoMousePressed

    private void btn_maestroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_maestroMousePressed
        if(SwingUtilities.isLeftMouseButton(evt)){//Verifica que se de click izquierdo
            Login_maestro ventana = new Login_maestro();
            ventana.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_maestroMousePressed

    private void btn_coordinadorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_coordinadorMousePressed
        if (SwingUtilities.isLeftMouseButton(evt)) {//Verifica que se de click izquierdo
            Login_coordinador ventana = new Login_coordinador();
            ventana.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_coordinadorMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_alumno;
    private javax.swing.JLabel btn_coordinador;
    private javax.swing.JLabel btn_maestro;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lb_info_alumno;
    private javax.swing.JLabel lb_info_coordinador;
    private javax.swing.JLabel lb_info_maestro;
    private javax.swing.JLabel logo_ita;
    private javax.swing.JPanel panel_contenido;
    private javax.swing.JPanel panel_logo;
    // End of variables declaration//GEN-END:variables
}
