/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alumno;

import conexion.Conexion;
import inicio.Inicio;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author ar275
 */
public class Login_alumno extends javax.swing.JFrame {

    /**
     * Creates new form Login_alumno
     */
    public Login_alumno() {
        initComponents();
        configuracion_ventana();
        cargar_img();
        //Centrar ventana
        this.setLocationRelativeTo(null);//La ventana aparece en el centro
    }
    
    //Funcion para toda la configuracion de la ventana 
    private void configuracion_ventana(){               
        //Añadir el listener para detectar cuando la ventana es redimensionada
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                int panelWidth = panel_login.getWidth();
                int panel_heigth = panel_login.getHeight() - panel_logo.getHeight();
                int newX = (fondo.getWidth() - panelWidth) / 2; // Calcular la nueva posición en 
                int newY = (fondo.getHeight() - panel_heigth)/2;
                panel_logo.setSize(fondo.getWidth(), panel_logo.getHeight());
                panel_login.setLocation(newX, newY);
                logo_ita.setLocation(newX, logo_ita.getY());            
            }
        });
    }
    
    //Funcion para cargar imagenes
    private void cargar_img(){
        //CARGAR EL LOGO PRINCIPAL DEL TEC
        Image logo_ita_img= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo_ITA.png"));
        logo_ita.setIcon(new ImageIcon(logo_ita_img.getScaledInstance(logo_ita.getWidth(), logo_ita.getHeight(), Image.SCALE_SMOOTH)));
        
        //CARGAR ICONO ALUMNO
        //Alumno
        Image icon_alumno= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icon_alumno_inicio.png"));
        lb_alumno_icon.setIcon(new ImageIcon(icon_alumno.getScaledInstance(lb_alumno_icon.getWidth(), lb_alumno_icon.getHeight(), Image.SCALE_SMOOTH)));
        
        //Icono inscripcioo
         Image icon_inscripcion = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icon_inscripcion.jpg"));
         lb_icon_inscripcion.setIcon(new ImageIcon(icon_inscripcion.getScaledInstance(lb_icon_inscripcion.getWidth(), lb_icon_inscripcion.getHeight(), Image.SCALE_SMOOTH)));
    }
    
    public void iniciar_sesion(String numControl, String password) throws SQLException {
        Conexion cx = new Conexion();//Variable para la conexion a la base de datos
        
        //Creaciond de consulta segura con Prepared
        String query = "SELECT * FROM alumno WHERE num_control = ? and password = ?";
        //Preparar consulta
        PreparedStatement ps = cx.conectar().prepareStatement(query);
        ps.setString(1, numControl);
        ps.setString(2, password);
        //Executar consulta
        ResultSet rs = ps.executeQuery();
        
        //Si los datos del alumno son correctos redigir al menu de Alumnos
        if(rs.next()){
            LocalDate fechaInicioSesion = LocalDate.now();//obtener la fecha del inicio de sesion
            LocalTime horaInicioSesion = LocalTime.now();
            MenuAlumno ventana = new MenuAlumno(numControl, fechaInicioSesion, horaInicioSesion);
            ventana.setVisible(true);
            this.dispose();
        }
        //Si los datos no son correctos
        else{
             JOptionPane.showMessageDialog(null, "Numero de control o contraseña incorrectos", "Usuario no valido", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        panel_logo = new javax.swing.JPanel();
        logo_ita = new javax.swing.JLabel();
        panel_login = new javax.swing.JPanel();
        lb_alumno_icon = new javax.swing.JLabel();
        entrada_numControl = new javax.swing.JTextField();
        password_entrada = new javax.swing.JPasswordField();
        lb_password = new javax.swing.JLabel();
        lb_numControl = new javax.swing.JLabel();
        btn_soporte = new javax.swing.JButton();
        btn_registro = new javax.swing.JButton();
        lb_icon_inscripcion = new javax.swing.JLabel();
        btn_iniciarSesion = new javax.swing.JButton();
        mostrar_password = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btn_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 630));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(null);

        panel_logo.setBackground(new java.awt.Color(255, 255, 255));
        panel_logo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_ita.setText("LOGO ITA");
        panel_logo.add(logo_ita, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 80));

        fondo.add(panel_logo);
        panel_logo.setBounds(0, 5, 800, 90);

        panel_login.setBackground(new java.awt.Color(255, 255, 255));
        panel_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_alumno_icon.setText("jLabel1");
        lb_alumno_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_login.add(lb_alumno_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 160, 160));
        panel_login.add(entrada_numControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 360, 50));
        panel_login.add(password_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 360, 50));

        lb_password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_password.setText("Contraseña");
        panel_login.add(lb_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 360, 40));

        lb_numControl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_numControl.setText("Número de control");
        panel_login.add(lb_numControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 360, 40));

        btn_soporte.setBackground(new java.awt.Color(153, 153, 153));
        btn_soporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_soporte.setText("?       SOPORTE");
        panel_login.add(btn_soporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 210, 40));

        btn_registro.setBackground(new java.awt.Color(0, 255, 0));
        btn_registro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_registro.setForeground(new java.awt.Color(255, 255, 255));
        btn_registro.setText("Registro");
        btn_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registroActionPerformed(evt);
            }
        });
        panel_login.add(btn_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 190, 40));

        lb_icon_inscripcion.setText("jLabel1");
        panel_login.add(lb_icon_inscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 190, 190));

        btn_iniciarSesion.setBackground(new java.awt.Color(0, 0, 255));
        btn_iniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_iniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btn_iniciarSesion.setText("Iniciar sesión");
        btn_iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarSesionActionPerformed(evt);
            }
        });
        panel_login.add(btn_iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 220, 40));

        mostrar_password.setText("Mostrar contraseña");
        mostrar_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrar_passwordActionPerformed(evt);
            }
        });
        panel_login.add(mostrar_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ALUMNO");
        panel_login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 510, 40));

        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        panel_login.add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 30));

        fondo.add(panel_login);
        panel_login.setBounds(0, 100, 800, 500);

        getContentPane().add(fondo, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrar_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrar_passwordActionPerformed
        //boton para mostrar y ocultar contraseña
        if (mostrar_password.isSelected()) {
            // Mostrar la contraseña en texto
            password_entrada.setEchoChar((char) 0);
            password_entrada.requestFocusInWindow();
        } else {
            // Ocultar la contraseña con el carácter por defecto (asterisco)
            password_entrada.setEchoChar('*');
            password_entrada.requestFocusInWindow();
        }
    }//GEN-LAST:event_mostrar_passwordActionPerformed

    private void btn_iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarSesionActionPerformed
        //Almacena los valores de entrada
        String numControl = entrada_numControl.getText().trim();
        String password = String.valueOf(password_entrada.getPassword());
        
        //Valida que los campos no sean vacios
        if(numControl.isEmpty() || password.isEmpty()){
           JOptionPane.showMessageDialog(null, "Por favor ingrese usuario y contraseña", "Campos Vacios", JOptionPane.ERROR_MESSAGE);
            return;
       }
        
        try { 
            iniciar_sesion(numControl,password);
        } catch (SQLException ex) {
            Logger.getLogger(Login_alumno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_iniciarSesionActionPerformed

    private void btn_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registroActionPerformed
        //Redirigir a la seccion de inscripcion
        InscripcionAlumno ventana = new InscripcionAlumno();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_registroActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        Inicio ventana = new Inicio();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_alumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciarSesion;
    private javax.swing.JButton btn_registro;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JButton btn_soporte;
    private javax.swing.JTextField entrada_numControl;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_alumno_icon;
    private javax.swing.JLabel lb_icon_inscripcion;
    private javax.swing.JLabel lb_numControl;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel logo_ita;
    private javax.swing.JCheckBox mostrar_password;
    private javax.swing.JPanel panel_login;
    private javax.swing.JPanel panel_logo;
    private javax.swing.JPasswordField password_entrada;
    // End of variables declaration//GEN-END:variables
}
