/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alumno;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author ar275
 */
public class Login_alumno extends javax.swing.JFrame {

    /**
     * Creates new form Login_alumno
     */
    public Login_alumno() {
        initComponents();
        configuracion_ventana();
        cargar_img();
    }
    
    //Funcion para toda la configuracion de la ventana 
    private void configuracion_ventana(){        
        //Centrar ventana
        this.setLocationRelativeTo(null);//La ventana aparece en el centro
    }
    
    //Funcion para cargar imagenes
    private void cargar_img(){
        //CARGAR EL LOGO PRINCIPAL DEL TEC
        Image logo_ita_img= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo_ITA.png"));
        logo_ita.setIcon(new ImageIcon(logo_ita_img.getScaledInstance(logo_ita.getWidth(), logo_ita.getHeight(), Image.SCALE_SMOOTH)));
        
        //CARGAR ICONO ALUMNO
        //Alumno
        Image icon_alumno= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icon_alumno_inicio.png"));
        lb_alumno_icon.setIcon(new ImageIcon(icon_alumno.getScaledInstance(lb_alumno_icon.getWidth(), lb_alumno_icon.getHeight(), Image.SCALE_SMOOTH)));
        
        //Icono inscripcioo
         Image icon_inscripcion = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icon_inscripcion.jpg"));
         lb_icon_inscripcion.setIcon(new ImageIcon(icon_inscripcion.getScaledInstance(lb_icon_inscripcion.getWidth(), lb_icon_inscripcion.getHeight(), Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo_ita = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lb_alumno_icon = new javax.swing.JLabel();
        entrada_numControl = new javax.swing.JTextField();
        entrada_password = new javax.swing.JPasswordField();
        lb_password = new javax.swing.JLabel();
        lb_numControl = new javax.swing.JLabel();
        btn_soporte = new javax.swing.JButton();
        btn_registro = new javax.swing.JButton();
        lb_icon_inscripcion = new javax.swing.JLabel();
        btn_iniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_ita.setText("LOGO ITA");
        jPanel1.add(logo_ita, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_alumno_icon.setText("jLabel1");
        lb_alumno_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(lb_alumno_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 160, 160));
        jPanel2.add(entrada_numControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 360, 50));
        jPanel2.add(entrada_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 360, 50));

        lb_password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_password.setText("Contraseña");
        jPanel2.add(lb_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 360, 40));

        lb_numControl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_numControl.setText("Número de control");
        jPanel2.add(lb_numControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 360, 40));

        btn_soporte.setBackground(new java.awt.Color(153, 153, 153));
        btn_soporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_soporte.setText("?       SOPORTE");
        jPanel2.add(btn_soporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 210, 40));

        btn_registro.setBackground(new java.awt.Color(0, 255, 0));
        btn_registro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_registro.setForeground(new java.awt.Color(255, 255, 255));
        btn_registro.setText("Registro");
        jPanel2.add(btn_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 190, 40));

        lb_icon_inscripcion.setText("jLabel1");
        jPanel2.add(lb_icon_inscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 190, 190));

        btn_iniciarSesion.setBackground(new java.awt.Color(0, 0, 255));
        btn_iniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_iniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btn_iniciarSesion.setText("Iniciar sesión");
        jPanel2.add(btn_iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 220, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 800, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_alumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciarSesion;
    private javax.swing.JButton btn_registro;
    private javax.swing.JButton btn_soporte;
    private javax.swing.JTextField entrada_numControl;
    private javax.swing.JPasswordField entrada_password;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_alumno_icon;
    private javax.swing.JLabel lb_icon_inscripcion;
    private javax.swing.JLabel lb_numControl;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel logo_ita;
    // End of variables declaration//GEN-END:variables
}
